name: Test

on:
  push:
    branches: [ main ]

jobs:
            
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose --env-file testing.env up -d
      
      - name: Sleep for 200 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '200s'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Scraping articles
        run: |
          curl -u test:test localhost:6800/schedule.json -d spider=news_spider -d project=default -d search_from=2022-04-04 -d search_to=2022-04-05 -d locale=en-gb -d crimes_file=list_of_crimes_english.txt
        shell: bash
      
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
        
      - name: Executing integration tests
        run: |
          python integration_test.py
        shell: bash
